"""Remove all state left by previous demo runs so re-runs are reproducible.

Usage:
    python demo/cleanup.py
"""

import subprocess
import sys
import os

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def sh(args, cwd=REPO, check=True):
    r = subprocess.run(["git"] + args, cwd=cwd, capture_output=True, text=True, check=False)
    if check and r.returncode != 0:
        print(r.stderr)
        sys.exit(f"git failed: {args}")
    return r


def main():
    worktrees_dir = os.path.join(REPO, ".worktrees")
    # Free any branch that is currently checked out in a leftover worktree.
    if os.path.isdir(worktrees_dir):
        for name in os.listdir(worktrees_dir):
            sh(["worktree", "remove", "--force", os.path.join(worktrees_dir, name)],
               check=False)
    sh(["worktree", "prune"], check=False)

    # Delete all fix branches from earlier runs.
    branches = sh(["branch", "--list", "fix/*"], check=False).stdout.strip()
    for line in branches.splitlines():
        b = line.strip().replace("*", "").strip()
        if b:
            sh(["branch", "-D", b], check=False)

    # Remove PR artifacts generated by earlier runs.
    pr_dir = os.path.join(REPO, "pull_requests")
    if os.path.isdir(pr_dir):
        for name in os.listdir(pr_dir):
            os.remove(os.path.join(pr_dir, name))

    print("Cleanup complete: no worktrees, no fix/* branches, no PR artifacts.")


if __name__ == "__main__":
    main()
